### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by gonzaloserrano** [fiorix/cat-o-licious#1]
- had to clone github.com/veandco/go-sdl2 and checkout to li/make-surface-implement-image branch to be able to go-get the project
- had to brew install pkgconfig to compile it

**Comment by fiorix** [comment]
Woah. That's unexpected... probably missed the pkgconfig bit because I already had it. For the sdl2 pkg, I should've used govendor to keep the right deps in place.

Would you submit a pr for this fix? If you don't care / can't / won't, I may do it myself later.

**Comment by gonzaloserrano** [comment]
Here you are https://github.com/fiorix/cat-o-licious/pull/2

**Comment by fiorix** [comment]
Thanks much! 💯
